- name: Wipe Logic
  block:
  - name: Stop Docker
    community.docker.docker_compose:
      project_src: "{{ docker_app_base_dir }}"
      state: absent
      remove_volumes: true
    ignore_errors: true

  - name: Remove files
    ansible.builtin.file:
      state: absent
      path: "{{ docker_app_base_dir }}"

  when: web_app_full_wipe | bool
  tags:
    - wipe