- name: Main tasks
  block:
  - name: Setup
    block:
      - name: Create directory
        ansible.builtin.file:
          state: directory
          path: "{{ docker_app_base_dir }}"
          mode: "0755"

      - name: Copy template
        ansible.builtin.template:
          src: docker-compose.yml.j2
          dest: "{{ docker_app_base_dir }}/docker-compose.yml"
          owner: root
          group: root
          mode: "0644"
    tags: deploy

  - name: Start app
    block:
      - name: Ensure docker
        ansible.builtin.service:
          name: "docker"
          enabled: true
          state: "started"

      - name: Run Docker-Compose
        ansible.builtin.docker_compose:
          state: present
          project_src: "{{ docker_app_base_dir }}"
          pull: true
    tags: deploy

  - name: Make Wipe
    import_tasks: tasks/0-wipe.yml
    tags: wipe

  tags:
    - web_app