name: App Python

on:
  push:
    paths:
      - "app_python/**"
      - ".github/workflows/app_python.yaml"

jobs:
  build:
    name: Building App
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Installing dependencies
        working-directory: app_python
        run: pip install -r requirements.py

      - name: Linter
        working-directory: app-python
        run: flake8
#        continue-on-error: true

      - name: Testing
        run: pytest